version: '3.8'

services:
  # ----------------------------
  # Banco de Dados PostgreSQL
  # ----------------------------
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: quarkus_pjc_2025_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root_pwd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ----------------------------
  # Armazenamento MinIO
  # ----------------------------
  minio:
    image: minio/minio:latest
    container_name: minio_storage
    restart: always
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: mudarSenha@123
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

  # ----------------------------
  # Aplicação em produção
  # Requer build com ./mvnw package
  # ----------------------------
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quarkus_pjc_2025_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/quarkus_pjc_2025_db
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: root_pwd
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: ROOTUSER
      MINIO_SECRET_KEY: mudarSenha@123

  # ----------------------------
  # Aplicação em desenvolvimento (modo quarkus:dev)
  # Usa Dockerfile.dev
  # ----------------------------
  dev-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: quarkus_pjc_2025_dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - minio
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/quarkus_pjc_2025_db
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: root_pwd
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: ROOTUSER
      MINIO_SECRET_KEY: mudarSenha@123

volumes:
  postgres_data:
  minio_data:
