-- Generated by the database client.
CREATE TABLE servidor_efetivo(
    se_id SERIAL NOT NULL,
    pes_id bigint NOT NULL,
    se_matricula varchar(20) NOT NULL,
    PRIMARY KEY(se_id),
    CONSTRAINT fk_servidor_efetivo_pessoa FOREIGN key(pes_id) REFERENCES pessoa(pes_id)
);